const $=(s,p=document)=>p.querySelector(s);const $$=(s,p=document)=>[...p.querySelectorAll(s)];const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function now(){return new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),1800)}

// navegação
const menuButton=$('#menuButton'),navLinks=$('#navLinks');menuButton.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menuButton.setAttribute('aria-expanded',open)});$$('#navLinks a').forEach(a=>a.addEventListener('click',()=>navLinks.classList.remove('open')));

// scroll progress + reveal
function updateProgress(){const h=document.documentElement;const max=h.scrollHeight-h.clientHeight;$('#scrollProgress').style.width=(max?scrollY/max*100:0)+'%'}window.addEventListener('scroll',updateProgress,{passive:true});updateProgress();
const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');revealObserver.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(el=>revealObserver.observe(el));

// counter hero
const counter=$('#heroCounter');let counted=false;const countObserver=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting&&!counted){counted=true;let start=0,target=1284,duration=900,t0=performance.now();function tick(t){const p=Math.min(1,(t-t0)/duration);counter.textContent=Math.round(target*(1-Math.pow(1-p,3))).toLocaleString('pt-BR');if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)}})},{threshold:.4});countObserver.observe(counter);

// demo tabs
function openDemo(name){$$('.demo-tab').forEach(b=>b.classList.toggle('active',b.dataset.demo===name));$$('.demo-panel').forEach(p=>p.classList.toggle('active',p.id===`demo-${name}`));}
$$('.demo-tab').forEach(b=>b.addEventListener('click',()=>openDemo(b.dataset.demo)));$$('[data-jump]').forEach(card=>card.addEventListener('click',()=>{openDemo(card.dataset.jump);$('#demos').scrollIntoView({behavior:'smooth',block:'start'})}));

function addMsg(box,text,who='bot'){const d=document.createElement('div');d.className=`msg ${who}`;d.innerHTML=`${text}<time>${now()}</time>`;box.appendChild(d);box.scrollTop=box.scrollHeight;return d}
function typing(box){const d=document.createElement('div');d.className='msg bot typing';d.innerHTML='<i></i><i></i><i></i>';box.appendChild(d);box.scrollTop=box.scrollHeight;return d}

// clínica
const clinic={messages:0,interest:null,stage:'Recepção'};const clinicChat=$('#clinicChat'),clinicInput=$('#clinicInput'),clinicTrace=$('#clinicTrace');
function clinicDecision(raw){const t=raw.toLowerCase();
 if(/(botox|toxina|ruga|testa)/.test(t))return{intent:'Procedimento',confidence:'97%',stage:'Qualificação',interest:'Toxina botulínica',status:'Interessado',action:'Entender objetivo',reply:'Claro 😊 A toxina botulínica é bastante procurada para suavizar linhas de expressão. Você já realizou esse procedimento alguma vez?'};
 if(/(limpeza|pele|cravo)/.test(t))return{intent:'Procedimento',confidence:'95%',stage:'Qualificação',interest:'Limpeza de pele',status:'Interessado',action:'Entender histórico',reply:'Claro 😊 A limpeza de pele ajuda na remoção de impurezas e na manutenção da saúde da pele. Você já fez esse procedimento antes?'};
 if(/(valor|preço|preco|quanto|custa)/.test(t))return{intent:'Preço',confidence:'98%',stage:'Encaminhamento',interest:clinic.interest||'A identificar',status:'Solicitou valor',action:'Encaminhar para avaliação',reply:'Os valores podem variar conforme o procedimento e a avaliação necessária. Posso organizar seu interesse e deixar tudo pronto para a equipe continuar o atendimento 😊'};
 if(/(agenda|agendar|horário|horario|marcar)/.test(t))return{intent:'Agendamento',confidence:'99%',stage:'Coleta',interest:clinic.interest||'Atendimento',status:'Quer agendar',action:'Coletar preferência',reply:'Perfeito 😊 Para simular o fluxo: você prefere atendimento pela manhã ou à tarde?'};
 if(/(manhã|manha)/.test(t))return{intent:'Preferência',confidence:'96%',stage:'Disponibilidade',interest:clinic.interest||'Atendimento',status:'Preferência: manhã',action:'Consultar agenda',reply:'Ótimo! Em uma operação real eu consultaria a agenda agora e apresentaria os horários disponíveis pela manhã.'};
 if(/(tarde|noite)/.test(t))return{intent:'Preferência',confidence:'96%',stage:'Disponibilidade',interest:clinic.interest||'Atendimento',status:'Preferência registrada',action:'Consultar agenda',reply:'Perfeito! Em uma operação real eu consultaria a agenda e apresentaria os melhores horários disponíveis para esse período.'};
 if(/(cancel|remarcar|reagendar)/.test(t))return{intent:'Alterar agenda',confidence:'97%',stage:'Validação',interest:'Agendamento existente',status:'Solicitou alteração',action:'Localizar agendamento',reply:'Consigo te orientar 😊 Em uma automação conectada, eu identificaria seu agendamento e seguiria com cancelamento ou reagendamento.'};
 return{intent:'Conversa geral',confidence:'82%',stage:'Entendimento',interest:clinic.interest||'Não identificado',status:'Em atendimento',action:'Entender melhor',reply:'Entendi 😊 Posso te ajudar com informações sobre procedimentos, valores, agendamento, reagendamento ou cancelamento. O que você gostaria de fazer?'};
}
function updateClinic(d){clinic.interest=d.interest;clinic.stage=d.stage;$('#clinicIntent').textContent=d.intent;$('#clinicConfidence').textContent=d.confidence;$('#clinicStage').textContent=d.stage;$('#ctxInterest').textContent=d.interest;$('#ctxStatus').textContent=d.status;$('#ctxAction').textContent=d.action;$('#ctxMessages').textContent=clinic.messages;clinicTrace.innerHTML=`<div class="trace-row done"><span>1</span><p><b>Mensagem recebida</b><small>Canal de demonstração</small></p><time>0 ms</time></div><div class="trace-row done"><span>2</span><p><b>Intenção interpretada</b><small>${d.intent} • ${d.confidence}</small></p><time>0,2s</time></div><div class="trace-row done"><span>3</span><p><b>Regra selecionada</b><small>${d.action}</small></p><time>0,4s</time></div>`}
async function sendClinic(text){text=text.trim();if(!text)return;clinic.messages++;recordDemo('clinica',`Mensagem: ${text.slice(0,70)}`);addMsg(clinicChat,text,'user');clinicInput.value='';const d=clinicDecision(text);updateClinic(d);const ty=typing(clinicChat);await sleep(550);ty.remove();addMsg(clinicChat,d.reply,'bot')}
$('#clinicForm').addEventListener('submit',e=>{e.preventDefault();sendClinic(clinicInput.value)});$$('[data-preset]').forEach(b=>b.addEventListener('click',()=>sendClinic(b.dataset.preset)));
function resetClinic(){Object.assign(clinic,{messages:0,interest:null,stage:'Recepção'});clinicChat.innerHTML=`<div class="date-chip">Hoje</div><div class="msg bot">Oi! 😊 Sou a Iana, assistente da clínica. Como posso te ajudar hoje?<time>${now()}</time></div>`;$('#clinicIntent').textContent='Aguardando';$('#clinicConfidence').textContent='—';$('#clinicStage').textContent='Recepção';$('#ctxInterest').textContent='Não identificado';$('#ctxStatus').textContent='Novo contato';$('#ctxAction').textContent='Entender necessidade';$('#ctxMessages').textContent='0';clinicTrace.innerHTML='<div class="trace-row done"><span>1</span><p><b>Sessão iniciada</b><small>Contexto demonstrativo criado</small></p><time>0 ms</time></div><div class="trace-row"><span>2</span><p><b>Aguardando mensagem</b><small>A automação reage conforme a intenção</small></p><time>—</time></div>';toast('Demo da clínica reiniciada')}

// reposição
function calculateStock(animated=false){const stock=Math.max(0,+$('#stockInput').value||0),avg=Math.max(0,+$('#avgInput').value||0),safety=Math.max(0,+$('#safetyInput').value||0),coverage=+$('#coverageSelect').value||1,demand=Math.round(avg*coverage),suggested=Math.max(0,demand+safety-stock);$('#stockProduct').textContent=$('#productSelect').value;$('#metricStock').textContent=`${stock} un.`;$('#metricDemand').textContent=`${demand} un.`;$('#metricSafety').textContent=`${safety} un.`;$('#metricCoverage').textContent=`${coverage.toFixed(1).replace('.',',')}x`;$('#suggestedQty').textContent=suggested;const ratio=demand?stock/demand:1,b=$('#riskBadge');b.className='risk '+(ratio<.35?'high':ratio<.7?'medium':'low');b.textContent=ratio<.35?'Risco alto':ratio<.7?'Atenção':'Risco baixo';$('#stockExplanation').textContent=suggested===0?'O estoque atual já cobre a demanda prevista e a margem de segurança definida. Nenhuma reposição adicional é sugerida agora.':`Demanda projetada de ${demand} unidades + ${safety} de segurança - ${stock} em estoque = ${suggested} unidades recomendadas.`;if(animated){recordDemo('reposicao',`Análise: ${$('#productSelect').value} • sugestão ${suggested} un.`);$('#stockLog').innerHTML='<div><i class="ok"></i><span>Estoque recebido</span><time>0,1s</time></div><div><i class="ok"></i><span>Histórico analisado</span><time>0,3s</time></div><div><i class="ok"></i><span>Demanda projetada</span><time>0,5s</time></div><div><i class="ok"></i><span>Pedido sugerido</span><time>0,7s</time></div>';toast('Análise concluída')}}
$('#analyzeStock').addEventListener('click',()=>calculateStock(true));function resetStock(){$('#productSelect').selectedIndex=0;$('#stockInput').value=8;$('#avgInput').value=28;$('#safetyInput').value=10;$('#coverageSelect').value='1';calculateStock(false);$('#stockLog').innerHTML='<div><i class="ok"></i><span>Dados da loja carregados</span><time>agora</time></div><div><i></i><span>Aguardando nova análise</span><time>—</time></div>';toast('Demo de reposição reiniciada')}calculateStock(false);

// imobiliária
const lead={step:0,intent:null,type:null,region:null,budget:null};const leadChat=$('#leadChat'),leadOptions=$('#leadOptions');const leadSteps=[{field:'type',q:'Perfeito. Qual tipo de imóvel você procura?',opts:['Casa','Apartamento','Terreno']},{field:'region',q:'Qual região ou bairro você prefere?',opts:['Costa e Silva','América','Centro','Outra região']},{field:'budget',q:'Qual faixa de investimento ou aluguel?',opts:['Até R$ 2 mil','R$ 2–3 mil','R$ 3–5 mil','Acima de R$ 5 mil']}];
function renderLeadOptions(opts){leadOptions.innerHTML=opts.map(o=>`<button type="button" data-answer="${o}">${o}</button>`).join('');$$('[data-answer]',leadOptions).forEach(b=>b.addEventListener('click',()=>answerLead(b.dataset.answer)))}
function updateCRM(){const filled=[lead.intent,lead.type,lead.region,lead.budget].filter(Boolean).length,pct=20+filled*20;$('#leadPercent').textContent=pct+'%';$('#leadProgress').style.width=pct+'%';$('#crmIntent').textContent=lead.intent||'—';$('#crmType').textContent=lead.type||'—';$('#crmRegion').textContent=lead.region||'—';$('#crmBudget').textContent=lead.budget||'—';const temp=$('#leadTemperature');if(filled<=1){temp.className='temperature cold';temp.textContent='Frio'}else if(filled<4){temp.className='temperature warm';temp.textContent='Morno'}else{temp.className='temperature hot';temp.textContent='Quente';$('#handoff').classList.add('ready');$('#handoff').innerHTML='<span>✓</span><div><b>Lead pronto para o corretor</b><p>Perfil organizado e contexto preparado para continuidade humana.</p></div>'}}
async function answerLead(answer){addMsg(leadChat,answer,'user');if(lead.step===0){lead.intent=answer==='Alugar'?'Aluguel':'Compra';lead.step=1}else{const cfg=leadSteps[lead.step-1];lead[cfg.field]=answer;lead.step++}updateCRM();leadOptions.innerHTML='';const ty=typing(leadChat);await sleep(500);ty.remove();if(lead.step<=leadSteps.length){const next=leadSteps[lead.step-1];addMsg(leadChat,next.q,'bot');renderLeadOptions(next.opts)}else{recordDemo('imobiliaria',`Lead qualificado: ${lead.intent} • ${lead.type} • ${lead.region}`);addMsg(leadChat,'Perfeito 😊 Já organizei seu perfil. Em uma operação real, agora eu registraria o lead no CRM e encaminharia ao corretor responsável com todo o contexto.','bot');leadOptions.innerHTML='<button type="button" disabled>Qualificação concluída ✓</button>'}}
function resetLead(){Object.assign(lead,{step:0,intent:null,type:null,region:null,budget:null});leadChat.innerHTML=`<div class="msg bot">Olá! 👋 Posso te ajudar a encontrar um imóvel. Você está procurando para comprar ou alugar?<time>${now()}</time></div>`;renderLeadOptions(['Alugar','Comprar']);$('#handoff').classList.remove('ready');$('#handoff').innerHTML='<span>↗</span><div><b>Encaminhamento inteligente</b><p>Quando o perfil estiver completo, o lead será preparado para o corretor.</p></div>';updateCRM();toast('Demo imobiliária reiniciada')}resetLead();

$$('[data-reset]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.reset==='clinica')resetClinic();if(b.dataset.reset==='reposicao')resetStock();if(b.dataset.reset==='imobiliaria')resetLead()}));

// processo ativado por scroll
const steps=$$('.process-step');const processObserver=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){steps.forEach(s=>s.classList.remove('active'));e.target.classList.add('active');const n=+e.target.dataset.step||1;$('#processProgress').style.width=(n/steps.length*100)+'%'}})},{threshold:.55});steps.forEach(s=>processObserver.observe(s));

// V5 — estado local, histórico, auto demos, compartilhamento e ROI
const STORAGE_KEY='gabrielAutomacoesDemoV5';
function loadDemoState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{runs:0,clinica:0,reposicao:0,imobiliaria:0,history:[]}}catch{return{runs:0,clinica:0,reposicao:0,imobiliaria:0,history:[]}}}
let demoState=loadDemoState();
function saveDemoState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(demoState));renderDemoState()}
function labelDemo(type){return type==='clinica'?'Clínica':type==='reposicao'?'Reposição':'Imobiliária'}
function recordDemo(type,detail){demoState.runs++;demoState[type]=(demoState[type]||0)+1;demoState.history.unshift({type,detail,time:new Date().toISOString()});demoState.history=demoState.history.slice(0,12);saveDemoState()}
function renderDemoState(){const map={dashRuns:demoState.runs,dashClinic:demoState.clinica,dashStock:demoState.reposicao,dashLead:demoState.imobiliaria};Object.entries(map).forEach(([id,v])=>{const el=$('#'+id);if(el)el.textContent=v||0});const list=$('#demoHistory'),count=$('#historyCount');if(!list)return;count.textContent=`${demoState.history.length} registro${demoState.history.length===1?'':'s'}`;list.innerHTML=demoState.history.length?demoState.history.map(h=>`<div class="history-row"><span>${labelDemo(h.type)}</span><p>${h.detail}</p><time>${new Date(h.time).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</time></div>`).join(''):'<div class="history-empty">Nenhuma execução ainda. Teste uma das demonstrações acima.</div>'}
renderDemoState();
$('#clearHistoryBtn')?.addEventListener('click',()=>{demoState={runs:0,clinica:0,reposicao:0,imobiliaria:0,history:[]};saveDemoState();toast('Histórico local limpo')});

let autoBusy=false;
function setAutoState(name,on){const panel=$(`#demo-${name}`);panel?.classList.toggle('auto-running',on);$$('[data-auto]').forEach(b=>b.disabled=on&&b.dataset.auto!==name)}
async function autoClinic(){if(autoBusy)return;autoBusy=true;openDemo('clinica');setAutoState('clinica',true);resetClinic();await sleep(450);for(const m of ['Quero fazer botox','Nunca fiz','Quanto custa?','Quero agendar','Prefiro de manhã']){await sendClinic(m);await sleep(650)}toast('Jornada automática da clínica concluída');setAutoState('clinica',false);autoBusy=false;setContextCTA('clinica')}
async function autoStock(){if(autoBusy)return;autoBusy=true;openDemo('reposicao');setAutoState('reposicao',true);resetStock();await sleep(450);$('#stockInput').value=6;$('#avgInput').value=34;$('#safetyInput').value=12;$('#coverageSelect').value='1.5';['stockInput','avgInput','safetyInput','coverageSelect'].forEach(id=>$('#'+id)?.classList.add('scenario-pulse'));await sleep(600);calculateStock(true);await sleep(700);toast('Cenário de reposição concluído');setAutoState('reposicao',false);autoBusy=false;setContextCTA('reposicao')}
async function autoLead(){if(autoBusy)return;autoBusy=true;openDemo('imobiliaria');setAutoState('imobiliaria',true);resetLead();await sleep(450);for(const a of ['Alugar','Casa','Costa e Silva','R$ 2–3 mil']){await answerLead(a);await sleep(600)}toast('Lead qualificado automaticamente');setAutoState('imobiliaria',false);autoBusy=false;setContextCTA('imobiliaria')}
$$('[data-auto]').forEach(b=>b.addEventListener('click',()=>({clinica:autoClinic,reposicao:autoStock,imobiliaria:autoLead}[b.dataset.auto]?.())));
$('#autoDemoBtn')?.addEventListener('click',async()=>{if(autoBusy)return;$('#demos').scrollIntoView({behavior:'smooth',block:'start'});await sleep(500);await autoClinic()});

function setContextCTA(name){const t=$('#contextCtaTitle'),p=$('#contextCtaText');if(!t||!p)return;const copy={clinica:['Quer um atendimento assim na sua clínica?','Posso adaptar a jornada, regras, agenda, procedimentos e encaminhamentos para a rotina real da sua equipe.'],reposicao:['Quer transformar estoque em decisão de pedido?','A solução pode ser adaptada às suas lojas, vendedores, produtos, regras de segurança e dados reais de venda.'],imobiliaria:['Quer qualificar seus leads antes do corretor assumir?','Posso adaptar perguntas, imóveis, regiões, CRM e critérios de lead quente à operação da sua imobiliária.']};const c=copy[name]||['Existe um processo repetitivo no seu negócio?','Posso analisar a rotina e transformar parte dela em uma automação demonstrável, integrada e preparada para crescer.'];t.textContent=c[0];p.textContent=c[1]}
$$('.demo-tab').forEach(b=>b.addEventListener('click',()=>setContextCTA(b.dataset.demo)));

$$('[data-share]').forEach(b=>b.addEventListener('click',async()=>{const name=b.dataset.share;const url=`${location.origin}${location.pathname}#demo-${name}`;try{await navigator.clipboard.writeText(url);toast('Link desta demonstração copiado')}catch{location.hash=`demo-${name}`;toast('Link da demonstração pronto para compartilhar')}}));
function openFromHash(){const m=location.hash.match(/^#demo-(clinica|reposicao|imobiliaria)$/);if(m){openDemo(m[1]);setContextCTA(m[1]);setTimeout(()=>$('#demos')?.scrollIntoView({behavior:'smooth',block:'start'}),120)}}
window.addEventListener('hashchange',openFromHash);openFromHash();

function calcROI(){const contacts=+$('#roiContacts')?.value||80,minutes=+$('#roiMinutes')?.value||6,percent=+$('#roiPercent')?.value||55;$('#roiContactsValue').textContent=contacts;$('#roiMinutesValue').textContent=`${minutes} min`;$('#roiPercentValue').textContent=`${percent}%`;const monthly=contacts*22*minutes/60,saved=monthly*percent/100;$('#roiManualHours').textContent=`${Math.round(monthly)}h`;$('#roiSavedHours').textContent=`${Math.round(saved)}h`;$('#roiDays').textContent=`${(saved/8).toFixed(1).replace('.',',')} dias`}
['roiContacts','roiMinutes','roiPercent'].forEach(id=>$('#'+id)?.addEventListener('input',calcROI));calcROI();
