const $=(s,p=document)=>p.querySelector(s);const $$=(s,p=document)=>[...p.querySelectorAll(s)];const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function now(){return new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),1800)}

// navegação
const menuButton=$('#menuButton'),navLinks=$('#navLinks');menuButton.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menuButton.setAttribute('aria-expanded',open)});$$('#navLinks a').forEach(a=>a.addEventListener('click',()=>navLinks.classList.remove('open')));

// scroll progress + reveal
function updateProgress(){const h=document.documentElement;const max=h.scrollHeight-h.clientHeight;$('#scrollProgress').style.width=(max?scrollY/max*100:0)+'%'}window.addEventListener('scroll',updateProgress,{passive:true});updateProgress();
const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');revealObserver.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(el=>revealObserver.observe(el));

// counter hero
const counter=$('#heroCounter');let counted=false;const countObserver=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting&&!counted){counted=true;let start=0,target=1284,duration=900,t0=performance.now();function tick(t){const p=Math.min(1,(t-t0)/duration);counter.textContent=Math.round(target*(1-Math.pow(1-p,3))).toLocaleString('pt-BR');if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)}})},{threshold:.4});countObserver.observe(counter);

// demo tabs
function openDemo(name){$$('.demo-tab').forEach(b=>b.classList.toggle('active',b.dataset.demo===name));$$('.demo-panel').forEach(p=>p.classList.toggle('active',p.id===`demo-${name}`));}
$$('.demo-tab').forEach(b=>b.addEventListener('click',()=>openDemo(b.dataset.demo)));$$('[data-jump]').forEach(card=>card.addEventListener('click',()=>{openDemo(card.dataset.jump);$('#demos').scrollIntoView({behavior:'smooth',block:'start'})}));

function addMsg(box,text,who='bot'){const d=document.createElement('div');d.className=`msg ${who}`;d.innerHTML=`${text}<time>${now()}</time>`;box.appendChild(d);box.scrollTop=box.scrollHeight;return d}
function typing(box){const d=document.createElement('div');d.className='msg bot typing';d.innerHTML='<i></i><i></i><i></i>';box.appendChild(d);box.scrollTop=box.scrollHeight;return d}

// clínica — motor de demonstração conversacional V6
const clinicChat=$('#clinicChat'),clinicInput=$('#clinicInput'),clinicTrace=$('#clinicTrace'),clinicQuick=$('#clinicQuick');
const CLINIC_STORAGE='zion_demo_clinic_v7';
const clinicServices={
  avaliacao_estetica:{label:'Avaliação Estética',duration:40,price:220,requiresEvaluation:false,aliases:['avaliação','avaliacao','consulta','diagnóstico','diagnostico'],what:'uma consulta individualizada para entender sua queixa, seus objetivos e o que faz sentido para o seu caso antes de definir um procedimento',how:'a profissional conversa sobre histórico, rotina e objetivos, avalia a região de interesse e orienta as possibilidades de tratamento',best:'quem ainda não sabe qual procedimento escolher, quer comparar opções ou precisa confirmar uma indicação',important:'A avaliação serve para montar uma indicação individualizada e alinhar expectativas com segurança.'},
  limpeza_de_pele_profunda:{label:'Limpeza de Pele Profunda',duration:60,price:280,requiresEvaluation:false,aliases:['limpeza de pele','limpeza','cravos','oleosidade','poros'],what:'um cuidado voltado à remoção de cravos e impurezas e à melhora da sensação de pele congestionada',how:'o atendimento envolve higienização, preparo da pele, extração cuidadosa quando indicada e finalização conforme a necessidade da pele',best:'cravos, excesso de oleosidade, poros obstruídos e manutenção dos cuidados com a pele',important:'Se houver acne inflamatória importante ou irritação, a indicação precisa ser avaliada antes.'},
  botox:{label:'Botox (toxina botulínica)',duration:40,price:950,requiresEvaluation:true,aliases:['botox','toxina','toxina botulínica','toxina botulinica','rugas','testa','patas de galinha','linhas de expressão'],what:'um procedimento com toxina botulínica usado para suavizar linhas de expressão relacionadas ao movimento muscular',how:'após avaliar os movimentos e a anatomia facial, pequenas quantidades são aplicadas em pontos específicos',best:'linhas de expressão na testa, entre as sobrancelhas e ao redor dos olhos',important:'Os pontos e a quantidade são individualizados, e o efeito é temporário.'},
  preenchimento:{label:'Preenchimento com Ácido Hialurônico',duration:50,price:1500,requiresEvaluation:true,aliases:['preenchimento','ácido hialurônico','acido hialuronico','lábios','labios','bigode chinês','sulco'],what:'um procedimento injetável utilizado para trabalhar volume, contorno e proporção em áreas selecionadas',how:'depois da avaliação facial, o produto é aplicado em pontos e planos definidos conforme o objetivo e a anatomia da região',best:'lábios, sulcos, contorno e pontos de sustentação, quando houver indicação',important:'A quantidade de produto e a área de aplicação só podem ser definidas corretamente após avaliação.'},
  bioestimulador:{label:'Bioestimulador de Colágeno',duration:75,price:1800,requiresEvaluation:true,aliases:['bioestimulador','colágeno','colageno','firmeza da pele'],what:'um tratamento injetável pensado para estimular gradualmente a produção de colágeno',how:'o produto é aplicado em pontos ou planos definidos na avaliação e a resposta acontece de forma progressiva',best:'flacidez, perda de firmeza e melhora global da qualidade da pele',important:'O resultado é gradual e o plano varia conforme região, produto e objetivo.'},
  hifu:{label:'Ultrassom Microfocado (HIFU)',duration:80,price:2200,requiresEvaluation:true,aliases:['hifu','ultrassom microfocado','papada','contorno facial'],what:'uma tecnologia de ultrassom focalizado utilizada em protocolos de firmeza e contorno facial',how:'o equipamento entrega energia em profundidades selecionadas, criando pontos térmicos controlados que estimulam remodelação tecidual',best:'flacidez facial, região de papada e melhora de contorno',important:'Região, parâmetros e expectativa de resultado precisam ser definidos na avaliação.'},
  laser:{label:'Laser para Melasma e Manchas',duration:50,price:1050,requiresEvaluation:true,aliases:['laser','melasma','manchas','mancha','pigmentação','pigmentacao'],what:'um protocolo com tecnologia de luz direcionado ao tratamento de alterações de pigmentação',how:'a energia luminosa é aplicada com parâmetros definidos para a pele e para o tipo de pigmentação',best:'manchas e melasma, depois de avaliar tipo de pele e característica da pigmentação',important:'Não é possível prometer clareamento específico sem avaliação; melasma pode ser recorrente.'},
  radiofrequencia:{label:'Radiofrequência Corporal',duration:60,price:280,requiresEvaluation:true,aliases:['radiofrequência','radiofrequencia','flacidez corporal','abdômen','abdomen','braços','coxas'],what:'uma tecnologia utilizada em protocolos corporais voltados principalmente para firmeza e textura da pele',how:'promove aquecimento controlado dos tecidos da região tratada, dentro de parâmetros definidos',best:'flacidez e melhora de textura em abdômen, braços e coxas',important:'A indicação e o número de sessões dependem da região e do objetivo.'},
  criolipolise:{label:'Criolipólise',duration:90,price:1400,requiresEvaluation:true,aliases:['criolipólise','criolipolise','gordura localizada','flancos'],what:'um procedimento corporal que utiliza resfriamento controlado em regiões selecionadas',how:'um aplicador é posicionado na região indicada e trabalha com resfriamento controlado durante o protocolo',best:'gordura localizada em áreas avaliadas como adequadas ao tratamento',important:'A indicação depende de avaliação da região, medidas e possíveis contraindicações.'}
};
const clinic={messages:0,customer:'Gabriel',intent:'Abertura',confidence:96,stage:'Recepção',serviceKey:null,interestKey:null,status:'Novo contato',action:'Entender necessidade',awaiting:null,date:null,time:null,slots:[],appointment:null,trace:[],scenario:'free',lastBot:'',handoff:false};
const normalizeClinic=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim();
const money=v=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL',minimumFractionDigits:2});
const pad=n=>String(n).padStart(2,'0');
function escapeClinic(v){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function clinicRich(v){return escapeClinic(v).replace(/\*([^*]+)\*/g,'<strong>$1</strong>').replace(/\n/g,'<br>')}
function clinicAddMsg(text,who='bot'){const d=document.createElement('div');d.className=`msg ${who} clinic-msg`;d.innerHTML=`<div>${clinicRich(text)}</div><time>${now()}${who==='user'?' ✓✓':''}</time>`;clinicChat.appendChild(d);clinicChat.scrollTop=clinicChat.scrollHeight;return d}
function clinicTyping(){const d=document.createElement('div');d.className='msg bot typing clinic-typing';d.innerHTML='<i></i><i></i><i></i>';clinicChat.appendChild(d);clinicChat.scrollTop=clinicChat.scrollHeight;return d}
function traceClinic(title,detail,state='done',duration='0,2s'){clinic.trace.unshift({title,detail,state,duration});clinic.trace=clinic.trace.slice(0,6);renderClinicTrace()}
function renderClinicTrace(){clinicTrace.innerHTML=clinic.trace.map((x,i)=>`<div class="trace-row ${x.state==='done'?'done':''}"><span>${clinic.trace.length-i}</span><p><b>${escapeClinic(x.title)}</b><small>${escapeClinic(x.detail)}</small></p><time>${x.duration}</time></div>`).join('')||'<div class="trace-row"><span>1</span><p><b>Aguardando mensagem</b><small>A sessão está pronta para receber uma entrada</small></p><time>—</time></div>'}
function clinicPersist(){try{localStorage.setItem(CLINIC_STORAGE,JSON.stringify({appointment:clinic.appointment}))}catch{}}
function clinicLoad(){try{const x=JSON.parse(localStorage.getItem(CLINIC_STORAGE)||'{}');if(x.appointment)clinic.appointment=x.appointment}catch{}}
function clinicServiceLabel(){return clinicServices[clinic.serviceKey]?.label||clinicServices[clinic.interestKey]?.label||'Não identificado'}
function updateClinicPanel(){
  $('#clinicIntent').textContent=clinic.intent;$('#clinicConfidence').textContent=`${clinic.confidence}%`;$('#clinicStage').textContent=clinic.stage;
  $('#ctxCustomer').textContent=clinic.customer;$('#ctxInterest').textContent=clinicServiceLabel();$('#ctxDate').textContent=clinic.date||'—';$('#ctxTime').textContent=clinic.time||'—';$('#ctxStatus').textContent=clinic.status;$('#ctxAction').textContent=clinic.action;$('#ctxMessages').textContent=`${clinic.messages} ${clinic.messages===1?'mensagem':'mensagens'}`;
  const card=$('#clinicAppointmentCard');if(clinic.appointment){card.hidden=false;$('#appointmentService').textContent=clinic.appointment.service;$('#appointmentDate').textContent=clinic.appointment.date;$('#appointmentTime').textContent=clinic.appointment.time;$('#appointmentProtocol').textContent=`Protocolo: ${clinic.appointment.protocol}`;const st=$('#appointmentState');st.textContent=clinic.appointment.status||'ativo';st.className=(clinic.appointment.status==='cancelado'?'cancelled':'')}else card.hidden=true;
  const sl=$('#clinicStatusLine');if(sl){sl.querySelector('small').textContent=clinic.handoff?'Conversa encaminhada para atendimento humano':clinic.stage==='Agendado'?'Agendamento confirmado':clinic.awaiting?'Aguardando sua resposta':'Atendimento em andamento'}
}
function setClinicMeta(intent,stage,status,action,confidence=96){clinic.intent=intent;clinic.stage=stage;clinic.status=status;clinic.action=action;clinic.confidence=confidence;updateClinicPanel()}
function detectClinicService(raw){const t=normalizeClinic(raw);for(const [key,s] of Object.entries(clinicServices)){if([s.label,...s.aliases].some(a=>t.includes(normalizeClinic(a))))return key}return null}
function serviceMenu(){return Object.values(clinicServices).map((s,i)=>`${i+1}) *${s.label}* — ${s.duration} min — a partir de ${money(s.price)}`).join('\n')}
function serviceByIndex(n){return Object.keys(clinicServices)[n-1]||null}
function serviceExplanation(key){const s=clinicServices[key];if(!s)return'';return `*${s.label}*\n\n*O que é:* É ${s.what}.\n\n*Como funciona:* ${s.how}.\n\n*É mais procurado para:* ${s.best}.\n\n⏱️ *Tempo médio:* ${s.duration} min\n💳 *Valor inicial:* ${money(s.price)}\n\nℹ️ *Importante:* ${s.important}${s.requiresEvaluation?'\n\nAntes do procedimento fazemos uma *Avaliação Estética* para confirmar indicação, região e planejamento com segurança.':''}`}
function setClinicQuick(items=[]){clinicQuick.innerHTML='';items.slice(0,4).forEach(item=>{const b=document.createElement('button');b.type='button';b.textContent=item.label;b.dataset.clinicReply=item.value;clinicQuick.appendChild(b)})}
function initialQuick(){setClinicQuick([{label:'Conhecer tratamentos',value:'Quais tratamentos vocês fazem?'},{label:'Quero cuidar da pele',value:'Quero algo para melhorar minha pele'},{label:'Agendar avaliação',value:'Quero agendar uma avaliação'},{label:'Já tenho agendamento',value:'Quero reagendar meu horário'}])}
function dayBr(d){return `${pad(d.getDate())}/${pad(d.getMonth()+1)}/${d.getFullYear()}`}
function parseClinicDate(raw){const t=normalizeClinic(raw),base=new Date();base.setHours(12,0,0,0);if(t.includes('depois de amanha')){base.setDate(base.getDate()+2);return dayBr(base)}if(t.includes('amanha')){base.setDate(base.getDate()+1);return dayBr(base)}const m=t.match(/\b(\d{1,2})\/(\d{1,2})(?:\/(\d{2,4}))?\b/);if(m){let y=m[3]?+m[3]:base.getFullYear();if(y<100)y+=2000;return `${pad(+m[1])}/${pad(+m[2])}/${y}`}const days=['domingo','segunda','terca','quarta','quinta','sexta','sabado'];for(let i=0;i<days.length;i++){if(t.includes(days[i])){let diff=(i-base.getDay()+7)%7;if(diff===0)diff=7;base.setDate(base.getDate()+diff);return dayBr(base)}}return null}
function generateClinicSlots(date,serviceKey){const seed=(date||'').split('').reduce((a,c)=>a+(+c||0),0)+(serviceKey||'').length;const pools=[['08:00','09:20','10:40'],['09:00','11:00','14:20'],['08:40','13:00','15:40'],['10:00','14:00','16:20']];return pools[seed%pools.length].map((time,i)=>({id:i+1,time,date}))}
function protocolClinic(){return `HZ-${new Date().getFullYear()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`}
function clinicBookingReply(){const a=clinic.appointment;return `✅ *Agendamento confirmado*\n\n${a.service}\n📅 ${a.date} às ${a.time}\n👤 ${clinic.customer}\n🔒 Protocolo: *${a.protocol}*\n\nMais perto do horário, o sistema enviaria automaticamente a confirmação e o lembrete. Se precisar reagendar ou cancelar, pode falar comigo por aqui.`}
function fakeExistingAppointment(){const d=new Date();d.setDate(d.getDate()+5);return{service:'Avaliação Estética',serviceKey:'avaliacao_estetica',date:dayBr(d),time:'14:00',protocol:'HZ-DEMO-4821',status:'ativo'}}
async function clinicReply(text,meta={}){clinic.lastBot=text;const ty=clinicTyping();await sleep(meta.fast?350:Math.min(1050,480+text.length*2.1));ty.remove();clinicAddMsg(text,'bot');traceClinic(meta.traceTitle||'Resposta preparada',meta.traceDetail||`${clinic.intent} • contexto preservado`,'done',meta.duration||'0,6s');updateClinicPanel()}
async function offerSlots(date){clinic.date=date;clinic.slots=generateClinicSlots(date,clinic.serviceKey||'avaliacao_estetica');clinic.awaiting='slot_choice';setClinicMeta('Consulta de agenda','Disponibilidade','Horários encontrados','Aguardar escolha do horário',99);traceClinic('Agenda consultada',`${clinic.slots.length} opções encontradas para ${date}`,'done','0,5s');setClinicQuick(clinic.slots.map(x=>({label:`${x.id} • ${x.time}`,value:String(x.id)})));await clinicReply(`Encontrei estes horários para *${clinicServices[clinic.serviceKey]?.label||'Avaliação Estética'}* em *${date}*:\n\n${clinic.slots.map(x=>`${x.id}) ${x.time}`).join('\n')}\n\nQual deles fica melhor para você?`,{traceTitle:'Horários apresentados',traceDetail:'Opções filtradas pela duração do procedimento'})}
async function chooseClinicService(key){clinic.serviceKey=key;clinic.interestKey=key;clinic.awaiting='first_time';const s=clinicServices[key];setClinicMeta('Interesse em procedimento','Orientação',`Interesse: ${s.label}`,'Entender histórico do paciente',98);traceClinic('Procedimento identificado',`${s.label} • catálogo consultado`,'done','0,2s');setClinicQuick([{label:'Nunca fiz',value:'Nunca fiz'},{label:'Já fiz antes',value:'Já fiz antes'},{label:'Quanto custa?',value:'Quanto custa?'}]);await clinicReply(`${serviceExplanation(key)}\n\nPara eu te orientar melhor: você já realizou esse procedimento alguma vez?`,{traceTitle:'Orientação montada',traceDetail:'Informação, duração, valor e histórico solicitado'})}
function isYes(t){return /^(sim|s|claro|pode|ok|okay|quero|isso|confirmo|fechado|beleza|sim quero)/.test(t)}
function isNo(t){return /^(nao|não|n|agora nao|agora não|deixa|prefiro nao|prefiro não)/.test(t)}
async function processClinic(raw){
  const text=raw.trim();if(!text)return;clinic.messages++;recordDemo('clinica',`Mensagem: ${text.slice(0,70)}`);clinicAddMsg(text,'user');clinicInput.value='';const t=normalizeClinic(text);traceClinic('Mensagem recebida',text.slice(0,72),'done','0 ms');
  const numeric=/^\d{1,2}$/.test(t)?+t:null;
  const service=detectClinicService(text);
  const asksSessions=/\b(sessoes|sessao|pacote|quantas.*tenho|quantas.*faltam|restantes)\b/.test(t);
  const asksServices=/\b(tratamentos|servicos|procedimentos|o que voces fazem|menu|lista)\b/.test(t);
  const asksPrice=/\b(valor|preco|quanto custa|custa quanto)\b/.test(t);
  const asksPayment=/\b(pagamento|pix|cartao|credito|debito|parcel)\b/.test(t);
  const asksHours=/\b(funcionamento|que horas|horario de atendimento|abre|fecha)\b/.test(t);
  const asksLocation=/\b(onde fica|endereco|localizacao|como chegar)\b/.test(t);
  const wantsReschedule=/\b(reagendar|remarcar|mudar.*horario|trocar.*horario)\b/.test(t);
  const wantsCancel=/\b(cancelar|desmarcar|cancelamento)\b/.test(t);
  const wantsHuman=/\b(atendente|humano|pessoa|equipe|responsavel|responsável)\b/.test(t);
  const wantsBook=/\b(agendar|marcar|agenda|vaga|horario)\b/.test(t);
  const broadSkin=/\b(pele|rosto)\b/.test(t)&&/\b(quero|melhorar|cuidar|tratamento|algo)\b/.test(t);
  const greeting=/^(oi|ola|olá|bom dia|boa tarde|boa noite|opa|e ai|e aí)[!. ]*$/.test(t);

  if(clinic.handoff){setClinicMeta('Atendimento humano','Handoff','Encaminhado','Equipe assume a conversa',100);return clinicReply('Sua conversa já está sinalizada para a equipe. Nesta demonstração, a partir daqui um atendente humano assumiria o WhatsApp.',{traceTitle:'Handoff preservado',traceDetail:'Automação não interfere após transferência'})}
  if(clinic.awaiting==='cancel_confirm'){
    if(isYes(t)){clinic.appointment={...clinic.appointment,status:'cancelado'};clinicPersist();clinic.awaiting=null;setClinicMeta('Cancelamento','Concluído','Agendamento cancelado','Encerrar atendimento',100);setClinicQuick([{label:'Ver novos horários',value:'Quero agendar outro horário'},{label:'Conhecer tratamentos',value:'Quais tratamentos vocês fazem?'}]);return clinicReply(`✅ *Cancelamento concluído*\n\nAtendimento: *${clinic.appointment.service}*\nProtocolo: *${clinic.appointment.protocol}*\n\nQuando quiser, posso verificar novos horários para você por aqui.`,{traceTitle:'Agendamento cancelado',traceDetail:'Status local atualizado e horário liberado'})}
    if(isNo(t)){clinic.awaiting=null;setClinicMeta('Cancelamento','Encerramento','Agendamento mantido','Aguardar nova solicitação',100);return clinicReply('Perfeito. Mantive seu agendamento como está. 😊',{traceTitle:'Cancelamento abortado',traceDetail:'Nenhuma alteração aplicada'})}
    return clinicReply('Só para confirmar com segurança: você deseja *cancelar* esse agendamento? Responda sim ou não.',{traceTitle:'Confirmação necessária',traceDetail:'Ação sensível exige confirmação explícita'})
  }
  if(clinic.awaiting==='booking_confirm'){
    if(isYes(t)){const s=clinicServices[clinic.serviceKey];clinic.appointment={service:s.label,serviceKey:clinic.serviceKey,date:clinic.date,time:clinic.time,protocol:protocolClinic(),status:'ativo'};clinic.awaiting=null;clinicPersist();setClinicMeta('Agendamento','Agendado','Agendamento confirmado','Enviar confirmação e lembretes',100);setClinicQuick([{label:'Como me preparar?',value:'Como devo me preparar?'},{label:'Reagendar',value:'Quero reagendar'},{label:'Cancelar',value:'Quero cancelar'}]);return clinicReply(clinicBookingReply(),{traceTitle:'Agendamento registrado',traceDetail:'Protocolo criado e lembretes programados','duration':'0,9s'})}
    if(isNo(t)){clinic.awaiting='slot_choice';clinic.time=null;setClinicMeta('Agendamento','Disponibilidade','Aguardando novo horário','Escolher outra opção',99);setClinicQuick(clinic.slots.map(x=>({label:`${x.id} • ${x.time}`,value:String(x.id)})));return clinicReply('Sem problema. Mantive as opções anteriores. Qual outro horário você prefere?',{traceTitle:'Confirmação recusada',traceDetail:'Reserva não foi criada'})}
  }
  if(clinic.awaiting==='slot_choice'){
    const slot=numeric?clinic.slots[numeric-1]:clinic.slots.find(x=>t.includes(x.time.replace(':',''))||t.includes(x.time));
    if(slot){clinic.time=slot.time;clinic.date=slot.date;clinic.awaiting='booking_confirm';setClinicMeta('Seleção de horário','Confirmação',`Horário escolhido: ${slot.time}`,'Confirmar agendamento',100);setClinicQuick([{label:'Confirmar',value:'Sim, confirmar'},{label:'Escolher outro',value:'Não, outro horário'}]);const s=clinicServices[clinic.serviceKey];return clinicReply(`Perfeito. Antes de confirmar, confere para mim:\n\n*${s.label}*\n📅 ${clinic.date}\n🕒 ${clinic.time}\n👤 ${clinic.customer}\n\nPosso confirmar esse agendamento?`,{traceTitle:'Slot selecionado',traceDetail:`${clinic.date} ${clinic.time} reservado temporariamente`})}
    const d=parseClinicDate(text);if(d)return offerSlots(d);
    return clinicReply('Essa opção não aparece na lista atual. Pode me dizer o *número do horário* ou enviar outra data?',{traceTitle:'Entrada não corresponde ao slot',traceDetail:'Mantendo opções atuais'})
  }
  if(clinic.awaiting==='date'){
    const d=parseClinicDate(text);if(d)return offerSlots(d);
    if(/manha|tarde/.test(t)){const d2=parseClinicDate('amanhã');await offerSlots(d2);return}
    return clinicReply('Pode me dizer uma data? Você pode escrever, por exemplo, *amanhã*, *sexta-feira* ou *18/09*.',{traceTitle:'Data necessária',traceDetail:'Aguardando referência de data'})
  }
  if(clinic.awaiting==='service_confirmation'&&isYes(t)){
    const original=clinic.serviceKey,s=clinicServices[original];if(s.requiresEvaluation&&original!=='avaliacao_estetica'){clinic.interestKey=original;clinic.serviceKey='avaliacao_estetica'}
    clinic.awaiting='date';setClinicMeta('Agendamento','Coleta de preferência',s.requiresEvaluation?'Avaliação necessária':'Procedimento definido','Coletar data desejada',99);setClinicQuick([{label:'Amanhã',value:'Amanhã'},{label:'Sexta-feira',value:'Sexta-feira'},{label:'Prefiro à tarde',value:'Amanhã à tarde'}]);return clinicReply(s.requiresEvaluation?`Perfeito. Para seguir com *${s.label}*, primeiro agendamos a *Avaliação Estética* para confirmar a indicação e planejar o atendimento.\n\nQual dia fica melhor para você?`:`Perfeito. Qual dia fica melhor para você fazer *${s.label}*?`,{traceTitle:'Regra de agenda aplicada',traceDetail:s.requiresEvaluation?'Interesse preservado; agenda direcionada para avaliação':'Procedimento liberado para agenda'})
  }
  if(clinic.awaiting==='service_confirmation'&&isNo(t)){clinic.awaiting=null;setClinicMeta('Orientação','Conversa','Sem agendamento','Responder nova dúvida',95);initialQuick();return clinicReply('Tudo bem 😊 Se quiser, posso explicar outro tratamento, comparar opções ou tirar alguma dúvida antes de pensar em agenda.',{traceTitle:'Agenda não iniciada',traceDetail:'Contexto do interesse foi preservado'})}
  if(clinic.awaiting==='first_time'&&(isYes(t)||isNo(t)||/nunca|primeira vez|ja fiz|já fiz/.test(t))){clinic.awaiting='service_confirmation';const s=clinicServices[clinic.serviceKey];setClinicMeta('Histórico do paciente','Orientação',/nunca|primeira vez|^nao$|^não$/.test(t)?'Primeira experiência':'Já realizou antes',s.requiresEvaluation?'Oferecer avaliação':'Oferecer horários',98);setClinicQuick([{label:s.requiresEvaluation?'Quero ver a avaliação':'Quero ver horários',value:'Sim, quero ver horários'},{label:'Quanto custa?',value:'Quanto custa?'},{label:'Ainda tenho dúvida',value:'Tenho outra dúvida'}]);return clinicReply(/nunca|primeira vez|^nao$|^não$/.test(t)?`Sem problema 😊 Sendo a primeira vez, a avaliação é justamente o momento para entender seu objetivo, histórico e tirar dúvidas com calma.\n\n${s.requiresEvaluation?`Para *${s.label}*, ela acontece antes do procedimento e serve para definir indicação e planejamento com segurança.`:`No caso de *${s.label}*, também conseguimos orientar todos os cuidados antes do atendimento.`}\n\nQuer que eu verifique os horários para você?`:`Ótimo. Mesmo para quem já fez antes, a profissional reavalia a região e o objetivo atual antes de definir o plano.\n\nQuer que eu verifique os horários disponíveis?`,{traceTitle:'Histórico interpretado',traceDetail:'Resposta adaptada à experiência informada'})}

  if(greeting){setClinicMeta('Saudação','Recepção','Novo contato','Entender necessidade',99);initialQuick();return clinicReply(`Olá, ${clinic.customer}. Seja muito bem-vindo à *Clínica Horizonte Estético*. 😊\n\nVocê já sabe qual procedimento quer, quer cuidar de algo específico — como pele, manchas, flacidez ou linhas de expressão — ou prefere conhecer os tratamentos?`,{traceTitle:'Sessão iniciada',traceDetail:'Cliente reconhecido pela sessão demonstrativa'})}
  if(wantsHuman){clinic.handoff=true;clinic.awaiting=null;setClinicMeta('Pedido de atendente','Handoff','Encaminhado para equipe','Pausar automação',100);setClinicQuick([]);return clinicReply('Claro. Vou encaminhar sua conversa para a equipe continuar por aqui. Todo o contexto que você já passou fica registrado para você não precisar repetir as informações.',{traceTitle:'Handoff criado',traceDetail:'Automação pausada para evitar conflito com atendimento humano'})}
  if(asksSessions){setClinicMeta('Consulta de sessões','Consulta de cadastro','Paciente localizado','Exibir saldo do pacote',99);setClinicQuick([{label:'Quero agendar próxima',value:'Quero agendar minha próxima sessão'},{label:'Falar com atendente',value:'Quero falar com um atendente'}]);traceClinic('Paciente localizado','Telefone da sessão demonstrativa → cadastro Gabriel','done','0,3s');return clinicReply('Encontrei um pacote demonstrativo vinculado ao seu cadastro:\n\n*Drenagem Linfática*\nContratadas: *10 sessões*\nRealizadas: *7 sessões*\nRestantes: *3 sessões*\n\nSe quiser, posso seguir para o agendamento da próxima sessão.',{traceTitle:'Saldo consultado',traceDetail:'10 contratadas • 7 realizadas • 3 restantes'})}
  if(wantsCancel){if(!clinic.appointment||clinic.appointment.status==='cancelado'){setClinicMeta('Cancelamento','Validação','Sem agendamento ativo','Solicitar referência',97);return clinicReply('Não encontrei um agendamento ativo nesta sessão de demonstração. Para testar o fluxo completo, use o cenário *Cancelamento* acima — ele carrega um agendamento fictício automaticamente.',{traceTitle:'Agenda consultada',traceDetail:'Nenhum agendamento ativo na sessão'})}clinic.awaiting='cancel_confirm';setClinicMeta('Cancelamento','Confirmação',`Agendamento localizado`, 'Confirmar cancelamento',100);setClinicQuick([{label:'Sim, cancelar',value:'Sim, cancelar'},{label:'Não, manter',value:'Não, manter'}]);return clinicReply(`Localizei este agendamento:\n\n*${clinic.appointment.service}*\n📅 ${clinic.appointment.date} às ${clinic.appointment.time}\n🔒 ${clinic.appointment.protocol}\n\nVocê deseja realmente cancelar?`,{traceTitle:'Agendamento localizado',traceDetail:'Confirmação obrigatória antes de cancelar'})}
  if(wantsReschedule){if(!clinic.appointment||clinic.appointment.status==='cancelado'){setClinicMeta('Reagendamento','Validação','Sem agendamento ativo','Solicitar referência',97);return clinicReply('Não encontrei um agendamento ativo nesta sessão. Para testar a jornada inteira, clique no cenário *Reagendamento* acima — ele cria um compromisso fictício para você alterar.',{traceTitle:'Agenda consultada',traceDetail:'Nenhum compromisso ativo encontrado'})}clinic.serviceKey=clinic.appointment.serviceKey;clinic.interestKey=clinic.serviceKey;clinic.awaiting='date';setClinicMeta('Reagendamento','Nova disponibilidade','Agendamento localizado','Coletar nova data',100);setClinicQuick([{label:'Amanhã',value:'Amanhã'},{label:'Sexta-feira',value:'Sexta-feira'}]);return clinicReply(`Claro. Encontrei seu agendamento atual:\n\n*${clinic.appointment.service}*\n📅 ${clinic.appointment.date} às ${clinic.appointment.time}\n\nQual nova data você prefere? O horário atual só será alterado depois que você confirmar o novo.`,{traceTitle:'Reagendamento iniciado',traceDetail:'Horário atual preservado até confirmação do novo'})}
  if(asksLocation){setClinicMeta('Localização','FAQ','Informação respondida','Aguardar nova solicitação',99);return clinicReply('Estamos usando um endereço fictício nesta demonstração: *Rua das Flores, 245 — Centro*.\n\nEm uma implantação real, eu envio o endereço correto da clínica e posso incluir o link de localização para o paciente abrir no mapa.',{traceTitle:'FAQ respondida',traceDetail:'Localização comercial consultada'})}
  if(asksHours){setClinicMeta('Horário de funcionamento','FAQ','Informação respondida','Aguardar nova solicitação',99);return clinicReply('O atendimento demonstrativo funciona de *segunda a sábado, das 07:00 às 18:00*, sempre com horário marcado.\n\nSe você me disser o procedimento e o dia que prefere, eu posso simular a consulta de disponibilidade.',{traceTitle:'FAQ respondida',traceDetail:'Horário comercial consultado'})}
  if(asksPayment){setClinicMeta('Formas de pagamento','FAQ','Informação respondida','Aguardar nova solicitação',99);return clinicReply('A clínica pode trabalhar com *Pix, cartão de débito e cartão de crédito*. Em procedimentos selecionados, o pagamento no cartão pode ser parcelado; as condições são confirmadas no fechamento.\n\nQuer saber o valor de algum procedimento específico?',{traceTitle:'FAQ respondida',traceDetail:'Condições comerciais consultadas'})}
  if(/como devo|preparo|antes do procedimento|antes da avaliacao/.test(t)){setClinicMeta('Orientação pré-atendimento','FAQ','Orientação enviada','Aguardar atendimento',96);return clinicReply('Alguns procedimentos pedem cuidados prévios específicos. Para a *Avaliação Estética*, basta vir com as informações sobre tratamentos anteriores, medicamentos de uso contínuo e o que você deseja melhorar.\n\nQuando o protocolo é definido, a orientação correta do procedimento é enviada antes do atendimento.',{traceTitle:'Orientação enviada',traceDetail:'Cuidados prévios selecionados conforme contexto'})}
  if(broadSkin&&!service){setClinicMeta('Orientação por objetivo','Qualificação','Objetivo: cuidados com a pele','Identificar principal queixa',97);clinic.awaiting=null;setClinicQuick([{label:'Cravos / oleosidade',value:'Tenho muitos cravos e oleosidade'},{label:'Manchas / melasma',value:'Quero tratar manchas e melasma'},{label:'Flacidez',value:'Quero melhorar flacidez'},{label:'Linhas de expressão',value:'Tenho linhas de expressão'}]);return clinicReply('*Claro. Vamos pelo que você quer melhorar na pele.* 😊\n\n• *Cravos, oleosidade ou poros obstruídos* → Limpeza de Pele Profunda\n• *Manchas ou melasma* → Laser para Melasma e Manchas\n• *Flacidez ou perda de firmeza* → Bioestimulador ou HIFU\n• *Linhas de expressão* → Botox, quando indicado\n\nQual dessas situações mais se parece com o que você quer melhorar?',{traceTitle:'Queixa ampla interpretada',traceDetail:'Opções filtradas por objetivo do cliente'})}
  if(service){return chooseClinicService(service)}
  if(asksPrice){if(clinic.serviceKey){const s=clinicServices[clinic.serviceKey];clinic.awaiting='service_confirmation';setClinicMeta('Valor','Orientação comercial',`Valor consultado: ${s.label}`,'Confirmar interesse',99);setClinicQuick([{label:'Quero ver horários',value:'Sim, quero ver horários'},{label:'Formas de pagamento',value:'Quais formas de pagamento?'}]);return clinicReply(`Para *${s.label}*, o valor demonstrativo é *a partir de ${money(s.price)}*.\n\n${s.requiresEvaluation?'Como a indicação e o planejamento são individualizados, primeiro fazemos a Avaliação Estética.':'O valor final é confirmado conforme o atendimento e eventuais particularidades do caso.'}\n\nQuer que eu verifique os horários?`,{traceTitle:'Valor consultado',traceDetail:`Tabela do procedimento • ${money(s.price)}`})}setClinicMeta('Valores','FAQ','Tabela consultada','Identificar procedimento',98);setClinicQuick([{label:'Botox',value:'Quanto custa botox?'},{label:'Limpeza de pele',value:'Quanto custa limpeza de pele?'},{label:'Avaliação',value:'Quanto custa avaliação?'}]);return clinicReply(`Posso te passar uma referência inicial:\n\n${serviceMenu()}\n\nSe preferir, me conta o que você gostaria de melhorar e eu te direciono para a opção mais adequada.`,{traceTitle:'Tabela consultada',traceDetail:'Valores iniciais apresentados com transparência'})}
  if(asksServices){setClinicMeta('Conhecer tratamentos','Catálogo','Menu apresentado','Aguardar escolha',99);clinic.awaiting='service_menu';setClinicQuick([{label:'1 • Avaliação',value:'1'},{label:'2 • Limpeza',value:'2'},{label:'3 • Botox',value:'3'},{label:'7 • Laser',value:'7'}]);return clinicReply(`Claro. Estes são os principais tratamentos:\n\n${serviceMenu()}\n\nPode me enviar *o número ou o nome do procedimento*. Se preferir, me diga o que gostaria de melhorar e eu te direciono.`,{traceTitle:'Catálogo carregado',traceDetail:`${Object.keys(clinicServices).length} procedimentos disponíveis`})}
  if(clinic.awaiting==='service_menu'&&numeric){const key=serviceByIndex(numeric);if(key)return chooseClinicService(key)}
  if(wantsBook){if(clinic.serviceKey){clinic.awaiting='date';setClinicMeta('Agendamento','Coleta de preferência','Procedimento definido','Coletar data',99);setClinicQuick([{label:'Amanhã',value:'Amanhã'},{label:'Sexta-feira',value:'Sexta-feira'}]);return clinicReply(`Perfeito. Qual dia fica melhor para você para *${clinicServices[clinic.serviceKey].label}*?`,{traceTitle:'Agendamento iniciado',traceDetail:'Procedimento já presente no contexto'})}setClinicMeta('Agendamento','Qualificação','Procedimento pendente','Identificar procedimento',96);setClinicQuick([{label:'Avaliação estética',value:'Quero agendar avaliação estética'},{label:'Limpeza de pele',value:'Quero agendar limpeza de pele'},{label:'Botox',value:'Quero fazer botox'}]);return clinicReply('Claro. Qual procedimento você deseja agendar? Se ainda não souber, pode me dizer o que gostaria de melhorar e eu te ajudo a escolher.',{traceTitle:'Agendamento iniciado',traceDetail:'Procedimento ainda não identificado'})}
  if(/^nao$|^não$/.test(t)&&clinic.serviceKey){setClinicMeta('Resposta contextual','Orientação','Paciente respondeu negativamente','Continuar conversa',94);return clinicReply(`Tudo bem. Sobre *${clinicServices[clinic.serviceKey].label}*, posso te explicar valores, cuidados, como funciona a avaliação ou verificar horários — o que seria mais útil para você agora?`,{traceTitle:'Resposta curta contextualizada',traceDetail:'A negativa foi associada ao assunto anterior'})}
  setClinicMeta('Conversa geral','Entendimento','Em atendimento','Esclarecer intenção',84);setClinicQuick([{label:'Ver tratamentos',value:'Quais tratamentos vocês fazem?'},{label:'Valores',value:'Quero saber os valores'},{label:'Agendar',value:'Quero agendar'},{label:'Falar com alguém',value:'Quero falar com um atendente'}]);return clinicReply('Entendi. Posso te ajudar com *procedimentos, valores, formas de pagamento, agendamento, reagendamento, cancelamento* ou até consultar um saldo de sessões demonstrativo. O que você gostaria de fazer?',{traceTitle:'Fallback contextual',traceDetail:'Nenhuma intenção específica atingiu o limiar de confiança'})
}
async function sendClinic(text){return processClinic(text)}
$('#clinicForm').addEventListener('submit',e=>{e.preventDefault();processClinic(clinicInput.value)});
clinicQuick.addEventListener('click',e=>{const b=e.target.closest('[data-clinic-reply]');if(b)processClinic(b.dataset.clinicReply)});
function resetClinic(options={}){
  Object.assign(clinic,{messages:0,intent:'Abertura',confidence:96,stage:'Recepção',serviceKey:null,interestKey:null,status:'Novo contato',action:'Entender necessidade',awaiting:null,date:null,time:null,slots:[],trace:[],scenario:options.scenario||'free',lastBot:'',handoff:false});
  if(options.clearAppointment!==false)clinic.appointment=null;clinicChat.innerHTML='<div class="date-chip">Hoje</div>';traceClinic('Sessão iniciada','Memória conversacional criada','done','0 ms');updateClinicPanel();initialQuick();clinicAddMsg(`Olá, ${clinic.customer}. Seja muito bem-vindo à *Clínica Horizonte Estético*. 😊\n\nVocê já sabe qual procedimento quer, quer cuidar de algo específico — como pele, manchas, flacidez ou linhas de expressão — ou prefere conhecer os tratamentos?`,'bot');
  $$('.scenario-btn').forEach(b=>b.classList.toggle('active',b.dataset.clinicScenario===clinic.scenario));
  if(!options.silent)toast('Demo da clínica reiniciada');
}
async function setClinicScenario(name){resetClinic({scenario:name,silent:true});if(name==='free'){toast('Conversa livre pronta');return}if(name==='reschedule'||name==='cancel'){clinic.appointment=fakeExistingAppointment();clinicPersist();updateClinicPanel();traceClinic('Agendamento demonstrativo carregado',`${clinic.appointment.date} ${clinic.appointment.time}`,'done','0,1s')}
  const intros={booking:'Quero fazer botox, nunca fiz antes',reschedule:'Quero reagendar meu horário',cancel:'Preciso cancelar meu agendamento',sessions:'Quantas sessões ainda tenho no meu pacote?'};toast('Cenário carregado');await sleep(350);processClinic(intros[name])
}
$$('[data-clinic-scenario]').forEach(b=>b.addEventListener('click',()=>setClinicScenario(b.dataset.clinicScenario)));
clinicLoad();resetClinic({scenario:'free',silent:true,clearAppointment:false});
// reposição — motor operacional V7
const stockCatalog=[
  {id:'hamburguer',name:'Pão de Hambúrguer',stock:6,avg:26,safety:8,pack:12},
  {id:'sanduiche',name:'Pão de Sanduíche',stock:18,avg:22,safety:8,pack:10},
  {id:'hotdog',name:'Pão de Hot Dog',stock:4,avg:24,safety:8,pack:12},
  {id:'sovado',name:'Pão Sovado',stock:11,avg:15,safety:6,pack:8},
  {id:'caseiro',name:'Pão Caseiro',stock:3,avg:12,safety:5,pack:6}
];
let stockState={products:[],analyzed:false,confirmed:false,protocol:null};
function stockSuggestion(p){const target=Math.ceil(p.avg*1.15+p.safety);const raw=Math.max(0,target-p.stock);return raw?Math.ceil(raw/p.pack)*p.pack:0}
function stockRisk(p){const cover=p.avg? p.stock/p.avg:2;return cover<.35?'high':cover<.75?'medium':'low'}
function renderStockProducts(){const box=$('#stockProducts');if(!box)return;box.innerHTML=stockState.products.map(p=>{const r=stockRisk(p);return `<article class="stock-product-row" data-stock-id="${p.id}"><div class="stock-product-main"><span class="sku-dot ${r}"></span><div><b>${p.name}</b><small>Venda média ${p.avg} un. • segurança ${p.safety} • caixa ${p.pack}</small></div></div><label><span>Estoque contado</span><div class="stepper"><button type="button" data-step-stock="-1" data-id="${p.id}">−</button><input inputmode="numeric" pattern="[0-9]*" min="0" type="number" value="${p.stock}" data-stock-input="${p.id}"><button type="button" data-step-stock="1" data-id="${p.id}">+</button></div></label><div class="stock-row-result"><span>Prévia</span><b>${stockSuggestion(p)} un.</b></div></article>`}).join('');
  $$('[data-stock-input]',box).forEach(i=>i.addEventListener('input',()=>{const p=stockState.products.find(x=>x.id===i.dataset.stockInput);p.stock=Math.max(0,+i.value||0);stockState.analyzed=false;$('#confirmOrder').disabled=true;const row=i.closest('.stock-product-row');const preview=row?.querySelector('.stock-row-result b');if(preview)preview.textContent=stockSuggestion(p)+' un.';}));
  $$('[data-step-stock]',box).forEach(b=>b.addEventListener('click',()=>{const p=stockState.products.find(x=>x.id===b.dataset.id);p.stock=Math.max(0,p.stock+(+b.dataset.stepStock));renderStockProducts()}));
}
function renderStockSummary(){const rows=stockState.products.map(p=>({...p,suggested:stockSuggestion(p),risk:stockRisk(p)}));const total=rows.reduce((a,p)=>a+p.suggested,0),critical=rows.filter(p=>p.risk==='high').length;const avgCover=rows.reduce((a,p)=>a+(p.avg?p.stock/p.avg:1),0)/rows.length;$('#stockCritical').textContent=critical;$('#stockUnits').textContent=total;$('#stockCoverage').textContent=(avgCover*7).toFixed(1).replace('.',',')+' dias';$('#stockTotalUnits').textContent=total;const badge=$('#riskBadge');badge.className='risk '+(critical>=2?'high':critical?'medium':'low');badge.textContent=critical>=2?'Risco alto':critical?'Atenção':'Risco controlado';$('#stockOrderLines').innerHTML=rows.map(p=>`<div class="order-line"><div><span class="sku-dot ${p.risk}"></span><p><b>${p.name}</b><small>${p.stock} em estoque • média ${p.avg}</small></p></div><strong>${p.suggested?`+${p.suggested}`:'OK'}</strong></div>`).join('');$('#stockExplanation').textContent=total?`A recomendação considera o giro recente, estoque de segurança e arredondamento por caixa fechada. ${critical} item${critical===1?' está':'s estão'} em condição crítica nesta visita.`:'O estoque contado já cobre a demanda prevista e a margem de segurança dos produtos.';}
function stockLog(lines){$('#stockLog').innerHTML=lines.map((x,i)=>`<div><i class="${x.ok?'ok':''}"></i><span>${x.text}</span><time>${x.time||['0,1s','0,3s','0,5s','0,8s'][i]||'agora'}</time></div>`).join('')}
async function calculateStock(animated=false){renderStockSummary();stockState.analyzed=true;$('#confirmOrder').disabled=false;if(animated){stockLog([{ok:true,text:'Contagem da loja recebida'},{ok:true,text:'Histórico de giro comparado'},{ok:true,text:'Risco por SKU calculado'},{ok:true,text:'Sugestão arredondada por caixa'}]);recordDemo('reposicao',`Visita analisada • ${$('#stockTotalUnits').textContent} unidades sugeridas`);toast('Sugestão de pedido pronta')}else stockLog([{ok:true,text:'Rota e mix da loja carregados',time:'agora'},{ok:false,text:'Aguardando conferência do vendedor',time:'—'}]);}
function resetStock(){stockState={products:stockCatalog.map(x=>({...x})),analyzed:false,confirmed:false,protocol:null};$('#orderConfirmation').hidden=true;$('#confirmOrder').disabled=true;renderStockProducts();renderStockSummary();stockLog([{ok:true,text:'Rota e mix da loja carregados',time:'agora'},{ok:false,text:'Aguardando conferência do vendedor',time:'—'}]);}
$('#analyzeStock')?.addEventListener('click',()=>calculateStock(true));
$('#simulateLowStock')?.addEventListener('click',()=>{const v=[2,5,1,4,0];stockState.products.forEach((p,i)=>p.stock=v[i]);renderStockProducts();renderStockSummary();stockLog([{ok:true,text:'Cenário de estoque crítico aplicado',time:'agora'},{ok:false,text:'Clique em gerar sugestão',time:'—'}]);toast('Estoque crítico simulado')});
$('#confirmOrder')?.addEventListener('click',()=>{if(!stockState.analyzed)return;stockState.confirmed=true;stockState.protocol='PED-'+new Date().getFullYear()+'-'+Math.random().toString(36).slice(2,7).toUpperCase();const total=$('#stockTotalUnits').textContent;const c=$('#orderConfirmation');c.hidden=false;c.innerHTML=`<span>✓</span><div><b>Pedido demonstrativo registrado</b><p>${total} unidades • ${stockState.protocol}</p><small>Em uma operação real, o pedido seguiria para o ERP/planilha e o gestor receberia a atualização.</small></div>`;stockLog([{ok:true,text:'Contagem da loja recebida'},{ok:true,text:'Sugestão calculada'},{ok:true,text:'Pedido confirmado pelo vendedor'},{ok:true,text:'Visita registrada no histórico'}]);recordDemo('reposicao',`Pedido confirmado • ${total} un. • ${stockState.protocol}`);toast('Pedido demonstrativo confirmado')});
resetStock();

// imobiliária — motor conversacional e matching V7
const realtyInventory=[
  {id:1,title:'Casa contemporânea • Costa e Silva',type:'Casa',region:'Costa e Silva',bedrooms:3,price:'R$ 2.850/mês',numeric:2850,feature:'3 quartos • 2 vagas • 118 m²',tag:'Mais aderente'},
  {id:2,title:'Sobrado geminado • América',type:'Casa',region:'América',bedrooms:3,price:'R$ 3.200/mês',numeric:3200,feature:'3 quartos • suíte • 105 m²',tag:'Boa opção'},
  {id:3,title:'Apartamento Garden • Costa e Silva',type:'Apartamento',region:'Costa e Silva',bedrooms:2,price:'R$ 2.650/mês',numeric:2650,feature:'2 quartos • garden • 1 vaga',tag:'Alternativa'},
  {id:4,title:'Apartamento • Centro',type:'Apartamento',region:'Centro',bedrooms:2,price:'R$ 2.300/mês',numeric:2300,feature:'2 quartos • 74 m² • 1 vaga',tag:'Bom custo'}
];
const lead={stage:'intent',intent:null,type:null,region:null,budget:null,bedrooms:null,timeline:null,selected:null,visit:null,messages:0};
const leadChat=$('#leadChat'),leadOptions=$('#leadOptions'),leadInput=$('#leadInput');
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function realtyMsg(text,who='bot'){return addMsg(leadChat,esc(text).replace(/\*([^*]+)\*/g,'<strong>$1</strong>').replace(/\n/g,'<br>'),who)}
function setLeadOptions(items=[]){leadOptions.innerHTML=items.map(o=>`<button type="button" data-lead-value="${esc(o.value??o)}">${esc(o.label??o)}</button>`).join('');$$('[data-lead-value]',leadOptions).forEach(b=>b.addEventListener('click',()=>processLead(b.dataset.leadValue)))}
function updateCRM(){const vals=[lead.intent,lead.type,lead.region,lead.budget,lead.bedrooms,lead.timeline].filter(Boolean).length,pct=Math.min(100,10+vals*15);$('#leadPercent').textContent=pct+'%';$('#leadProgress').style.width=pct+'%';$('#crmIntent').textContent=lead.intent||'—';$('#crmType').textContent=lead.type||'—';$('#crmRegion').textContent=lead.region||'—';$('#crmBudget').textContent=lead.budget||'—';$('#crmBedrooms').textContent=lead.bedrooms?lead.bedrooms+' quartos':'—';$('#crmTimeline').textContent=lead.timeline||'—';const temp=$('#leadTemperature'),handoff=$('#handoff');if(vals<=2){temp.className='temperature cold';temp.textContent='Frio';$('#realtyCrmState').textContent='Qualificando'}else if(vals<6){temp.className='temperature warm';temp.textContent='Morno';$('#realtyCrmState').textContent='Perfil em construção'}else{temp.className='temperature hot';temp.textContent='Quente';$('#realtyCrmState').textContent=lead.visit?'Visita agendada':'Lead qualificado'}if(vals===6){handoff.classList.add('ready');handoff.innerHTML='<span>✓</span><div><b>Lead qualificado</b><p>Perfil completo. O sistema já pode cruzar preferências com a carteira e preparar o contexto para o corretor.</p></div>'}else{handoff.classList.remove('ready');handoff.innerHTML='<span>↗</span><div><b>Qualificação em andamento</b><p>A Iana ainda está coletando informações para encontrar os imóveis mais aderentes.</p></div>'}}
function renderProperties(){const exact=realtyInventory.filter(p=>(!lead.type||p.type===lead.type)&&(!lead.region||p.region===lead.region));const alternatives=realtyInventory.filter(p=>(!lead.type||p.type===lead.type)&&!exact.some(x=>x.id===p.id));let list=[...exact,...alternatives].slice(0,3);if(!list.length)list=realtyInventory.slice(0,3);const wrap=$('#propertyMatches');wrap.hidden=false;$('#matchCount').textContent=`${list.length} opções`;$('#propertyList').innerHTML=list.map((p,i)=>`<article class="property-card ${i===0?'best':''}"><div class="property-photo"><span>${i===0?'★':'⌂'}</span><small>${i===0?'Mais aderente':p.tag}</small></div><div class="property-info"><span>${p.region}</span><h4>${p.title}</h4><p>${p.feature}</p><strong>${p.price}</strong><button type="button" data-property-id="${p.id}">Tenho interesse</button></div></article>`).join('');$$('[data-property-id]').forEach(b=>b.addEventListener('click',()=>processLead('property:'+b.dataset.propertyId)));return list}
function profileCompleteReply(){const list=renderProperties();lead.stage='property';setLeadOptions(list.map((p,i)=>({label:`Ver opção ${i+1}`,value:'property:'+p.id})));return `Perfeito, Gabriel. Já tenho um perfil bem definido:\n\n• *${lead.intent}*\n• ${lead.type} em ${lead.region}\n• ${lead.bedrooms} quartos\n• ${lead.budget}\n• Prazo: ${lead.timeline}\n\nCruzei essas preferências com uma carteira demonstrativa e encontrei *${list.length} imóveis compatíveis*. Eles apareceram ao lado. Qual deles você quer conhecer melhor?`}
function visitSlots(){const d=new Date();const fmt=n=>{const x=new Date(d);x.setDate(x.getDate()+n);return x.toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'2-digit'})};return [{label:`${fmt(1)} • 10:00`,value:`slot:${fmt(1)}|10:00`},{label:`${fmt(1)} • 15:30`,value:`slot:${fmt(1)}|15:30`},{label:`${fmt(2)} • 09:00`,value:`slot:${fmt(2)}|09:00`}];}
async function leadBot(text,opts=[]){const ty=typing(leadChat);await sleep(520);ty.remove();realtyMsg(text,'bot');setLeadOptions(opts);updateCRM()}
async function processLead(raw){const text=String(raw||'').trim();if(!text)return;lead.messages++;realtyMsg(text.startsWith('property:')?'Tenho interesse neste imóvel':text.startsWith('slot:')?'Esse horário funciona para mim':text,'user');leadInput.value='';setLeadOptions([]);const t=text.toLowerCase();
  if(text.startsWith('property:')){lead.selected=realtyInventory.find(p=>p.id===+text.split(':')[1]);lead.stage='property_action';return leadBot(`Ótima escolha. *${lead.selected.title}* está dentro do perfil que você passou.\n\n${lead.selected.feature}\n${lead.selected.price}\n\nQuer que eu verifique horários disponíveis para uma visita?`,[{label:'Ver horários de visita',value:'agendar visita'},{label:'Ver outras opções',value:'outras opções'}])}
  if(text.startsWith('slot:')){const [date,time]=text.slice(5).split('|');lead.visit={date,time,protocol:'VIS-'+Math.random().toString(36).slice(2,7).toUpperCase()};lead.stage='done';$('#visitPreview').hidden=false;$('#visitProperty').textContent=lead.selected.title;$('#visitDate').textContent=date;$('#visitTime').textContent=time;$('#visitProtocol').textContent='Protocolo: '+lead.visit.protocol;updateCRM();recordDemo('imobiliaria',`Visita agendada • ${lead.selected.region} • ${date} ${time}`);return leadBot(`✅ *Visita confirmada*\n\n${lead.selected.title}\n📅 ${date}\n🕐 ${time}\n🔒 ${lead.visit.protocol}\n\nO corretor receberia agora seu perfil completo, o imóvel escolhido e os dados da visita. Você não precisaria repetir tudo novamente.`,[{label:'Encerrar demonstração',value:'obrigado'}])}
  if(lead.stage==='intent'){lead.intent=t.includes('compr')?'Compra':'Aluguel';lead.stage='type';return leadBot(`Perfeito. Vamos procurar para *${lead.intent.toLowerCase()}*. Que tipo de imóvel faz mais sentido para você?`,['Casa','Apartamento','Terreno'])}
  if(lead.stage==='type'){lead.type=t.includes('apart')?'Apartamento':t.includes('terr')?'Terreno':'Casa';lead.stage='region';return leadBot('Certo. Qual bairro ou região você prefere em Joinville?',['Costa e Silva','América','Centro','Outra região'])}
  if(lead.stage==='region'){lead.region=text==='Outra região'?'Sem preferência definida':text;lead.stage='bedrooms';return leadBot('E quantos quartos você precisa?',['1 quarto','2 quartos','3 quartos','4 ou mais'])}
  if(lead.stage==='bedrooms'){lead.bedrooms=parseInt(text)||4;lead.stage='budget';return leadBot(`Entendi. E qual faixa de valor você pretende trabalhar para ${lead.intent.toLowerCase()}?`,lead.intent==='Aluguel'?['Até R$ 2 mil','R$ 2–3 mil','R$ 3–4 mil','Acima de R$ 4 mil']:['Até R$ 400 mil','R$ 400–600 mil','R$ 600–900 mil','Acima de R$ 900 mil'])}
  if(lead.stage==='budget'){lead.budget=text;lead.stage='timeline';return leadBot('Última pergunta para eu priorizar as opções certas: quando você pretende se mudar ou fechar negócio?',['O quanto antes','Em até 30 dias','1 a 3 meses','Só pesquisando'])}
  if(lead.stage==='timeline'){lead.timeline=text;updateCRM();const reply=profileCompleteReply();const list=renderProperties();return leadBot(reply,list.map((p,i)=>({label:`Ver opção ${i+1}`,value:'property:'+p.id})))}
  if(lead.stage==='property_action'){
    if(t.includes('outra')){lead.stage='property';const list=renderProperties();return leadBot('Claro. Separei novamente as opções compatíveis. Escolha outra para eu detalhar.',list.map((p,i)=>({label:`Ver opção ${i+1}`,value:'property:'+p.id})))}
    lead.stage='visit';const slots=visitSlots();return leadBot(`Consultei uma agenda demonstrativa para *${lead.selected.title}*. Tenho estes horários próximos:\n\n${slots.map((s,i)=>`${i+1}) ${s.label}`).join('\n')}\n\nQual fica melhor para você?`,slots)}
  if(lead.stage==='property'){const list=renderProperties();return leadBot('Escolha uma das opções que apareceram no painel para eu continuar.',list.map((p,i)=>({label:`Ver opção ${i+1}`,value:'property:'+p.id})))}
  if(lead.stage==='done')return leadBot('Perfeito 😊 A demonstração está concluída. Em produção, o histórico ficaria registrado no CRM e o corretor seguiria a conversa com todo o contexto.');
  return leadBot('Posso continuar sua busca. Use uma das opções abaixo para avançarmos.')
}
function resetLead(){Object.assign(lead,{stage:'intent',intent:null,type:null,region:null,budget:null,bedrooms:null,timeline:null,selected:null,visit:null,messages:0});leadChat.innerHTML='';$('#propertyMatches').hidden=true;$('#visitPreview').hidden=true;$('#realtyCrmState').textContent='Novo lead';updateCRM();realtyMsg('Olá, Gabriel! Aqui é a Iana, da *Horizonte Prime Imóveis*. 😊\n\nPosso te ajudar a encontrar um imóvel e já deixar tudo organizado para o corretor. Você está procurando para *comprar* ou *alugar*?','bot');setLeadOptions(['Alugar','Comprar']);}
$('#leadForm')?.addEventListener('submit',e=>{e.preventDefault();processLead(leadInput.value)});
resetLead();

$$('[data-reset]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.reset==='clinica')resetClinic();if(b.dataset.reset==='reposicao'){resetStock();toast('Demo de reposição reiniciada')}if(b.dataset.reset==='imobiliaria'){resetLead();toast('Demo imobiliária reiniciada')}}));

// processo ativado por scroll
const steps=$$('.process-step');const processObserver=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){steps.forEach(s=>s.classList.remove('active'));e.target.classList.add('active');const n=+e.target.dataset.step||1;$('#processProgress').style.width=(n/steps.length*100)+'%'}})},{threshold:.55});steps.forEach(s=>processObserver.observe(s));

// V5 — estado local, histórico, auto demos, compartilhamento e ROI
const STORAGE_KEY='zionAutomacoesDemoV8';
function loadDemoState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{runs:0,clinica:0,reposicao:0,imobiliaria:0,history:[]}}catch{return{runs:0,clinica:0,reposicao:0,imobiliaria:0,history:[]}}}
let demoState=loadDemoState();
function saveDemoState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(demoState));renderDemoState()}
function labelDemo(type){return type==='clinica'?'Clínica':type==='reposicao'?'Reposição':'Imobiliária'}
function recordDemo(type,detail){demoState.runs++;demoState[type]=(demoState[type]||0)+1;demoState.history.unshift({type,detail,time:new Date().toISOString()});demoState.history=demoState.history.slice(0,12);saveDemoState()}
function renderDemoState(){const map={dashRuns:demoState.runs,dashClinic:demoState.clinica,dashStock:demoState.reposicao,dashLead:demoState.imobiliaria};Object.entries(map).forEach(([id,v])=>{const el=$('#'+id);if(el)el.textContent=v||0});const list=$('#demoHistory'),count=$('#historyCount');if(!list)return;count.textContent=`${demoState.history.length} registro${demoState.history.length===1?'':'s'}`;list.innerHTML=demoState.history.length?demoState.history.map(h=>`<div class="history-row"><span>${labelDemo(h.type)}</span><p>${h.detail}</p><time>${new Date(h.time).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</time></div>`).join(''):'<div class="history-empty">Nenhuma execução ainda. Teste uma das demonstrações acima.</div>'}
renderDemoState();
$('#clearHistoryBtn')?.addEventListener('click',()=>{demoState={runs:0,clinica:0,reposicao:0,imobiliaria:0,history:[]};saveDemoState();toast('Histórico local limpo')});

let autoBusy=false;
function setAutoState(name,on){const panel=$(`#demo-${name}`);panel?.classList.toggle('auto-running',on);$$('[data-auto]').forEach(b=>b.disabled=on&&b.dataset.auto!==name)}
async function autoClinic(){if(autoBusy)return;autoBusy=true;openDemo('clinica');setAutoState('clinica',true);resetClinic({scenario:'booking',silent:true});await sleep(450);for(const m of ['Quero fazer botox','Nunca fiz','Sim, quero ver horários','Amanhã','1','Sim, confirmar']){await sendClinic(m);await sleep(520)}toast('Jornada completa: agendamento confirmado');setAutoState('clinica',false);autoBusy=false;setContextCTA('clinica')}
async function autoStock(){if(autoBusy)return;autoBusy=true;openDemo('reposicao');setAutoState('reposicao',true);resetStock();await sleep(450);const critical=[2,4,1,5,0];stockState.products.forEach((p,i)=>p.stock=critical[i]);renderStockProducts();renderStockSummary();await sleep(650);await calculateStock(true);await sleep(700);$('#confirmOrder')?.click();await sleep(500);toast('Jornada completa: pedido demonstrativo registrado');setAutoState('reposicao',false);autoBusy=false;setContextCTA('reposicao')}
async function autoLead(){if(autoBusy)return;autoBusy=true;openDemo('imobiliaria');setAutoState('imobiliaria',true);resetLead();await sleep(450);for(const a of ['Alugar','Casa','Costa e Silva','3 quartos','R$ 2–3 mil','Em até 30 dias','property:1','agendar visita']){await processLead(a);await sleep(520)}const slot=visitSlots()[0];await processLead(slot.value);toast('Jornada completa: visita agendada');setAutoState('imobiliaria',false);autoBusy=false;setContextCTA('imobiliaria')}
$$('[data-auto]').forEach(b=>b.addEventListener('click',()=>({clinica:autoClinic,reposicao:autoStock,imobiliaria:autoLead}[b.dataset.auto]?.())));
$('#autoDemoBtn')?.addEventListener('click',async()=>{if(autoBusy)return;$('#demos').scrollIntoView({behavior:'smooth',block:'start'});await sleep(500);await autoClinic()});

function setContextCTA(name){const t=$('#contextCtaTitle'),p=$('#contextCtaText');if(!t||!p)return;const copy={clinica:['Quer um atendimento assim na sua clínica?','Posso adaptar a jornada, regras, agenda, procedimentos e encaminhamentos para a rotina real da sua equipe.'],reposicao:['Quer transformar estoque em decisão de pedido?','A solução pode ser adaptada às suas lojas, vendedores, produtos, regras de segurança e dados reais de venda.'],imobiliaria:['Quer qualificar seus leads antes do corretor assumir?','Posso adaptar perguntas, imóveis, regiões, CRM e critérios de lead quente à operação da sua imobiliária.']};const c=copy[name]||['Existe um processo repetitivo no seu negócio?','Posso analisar a rotina e transformar parte dela em uma automação demonstrável, integrada e preparada para crescer.'];t.textContent=c[0];p.textContent=c[1]}
$$('.demo-tab').forEach(b=>b.addEventListener('click',()=>setContextCTA(b.dataset.demo)));

$$('[data-share]').forEach(b=>b.addEventListener('click',async()=>{const name=b.dataset.share;const url=`${location.origin}${location.pathname}#demo-${name}`;try{await navigator.clipboard.writeText(url);toast('Link desta demonstração copiado')}catch{location.hash=`demo-${name}`;toast('Link da demonstração pronto para compartilhar')}}));
function openFromHash(){const m=location.hash.match(/^#demo-(clinica|reposicao|imobiliaria)$/);if(m){openDemo(m[1]);setContextCTA(m[1]);setTimeout(()=>$('#demos')?.scrollIntoView({behavior:'smooth',block:'start'}),120)}}
window.addEventListener('hashchange',openFromHash);openFromHash();

function calcROI(){const contacts=+$('#roiContacts')?.value||80,minutes=+$('#roiMinutes')?.value||6,percent=+$('#roiPercent')?.value||55;$('#roiContactsValue').textContent=contacts;$('#roiMinutesValue').textContent=`${minutes} min`;$('#roiPercentValue').textContent=`${percent}%`;const monthly=contacts*22*minutes/60,saved=monthly*percent/100;$('#roiManualHours').textContent=`${Math.round(monthly)}h`;$('#roiSavedHours').textContent=`${Math.round(saved)}h`;$('#roiDays').textContent=`${(saved/8).toFixed(1).replace('.',',')} dias`}
['roiContacts','roiMinutes','roiPercent'].forEach(id=>$('#'+id)?.addEventListener('input',calcROI));calcROI();

// V8 — modo imersivo e refinamentos de experiência
const demoShell=document.querySelector('.demo-shell');
const focusClose=document.getElementById('focusClose');
function enterDemoFocus(name){
  if(!demoShell)return;
  openDemo(name);
  demoShell.classList.add('focus-mode');
  document.body.classList.add('demo-focus');
  focusClose?.classList.add('visible');
  focusClose?.focus({preventScroll:true});
}
function exitDemoFocus(){
  demoShell?.classList.remove('focus-mode');
  document.body.classList.remove('demo-focus');
  focusClose?.classList.remove('visible');
}
document.querySelectorAll('[data-focus]').forEach(btn=>btn.addEventListener('click',()=>enterDemoFocus(btn.dataset.focus)));
focusClose?.addEventListener('click',exitDemoFocus);
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.classList.contains('demo-focus'))exitDemoFocus()});

// No celular, mantém o campo visível quando o teclado abre.
if(window.visualViewport){
  window.visualViewport.addEventListener('resize',()=>{
    if(!document.body.classList.contains('demo-focus'))return;
    document.documentElement.style.setProperty('--vvh',`${window.visualViewport.height}px`);
  });
}

// V9 — estimador comercial e continuidade entre demo → proposta
const estimatorState={lastSolution:localStorage.getItem('zion_last_interest')||'clinica'};
const solutionCatalog={
  clinica:{name:'Zion Atendimento Inteligente',desc:'Atendimento automatizado com contexto, regras de negócio e jornada de agendamento.',base:[1800,2800],monthly:[397,697],features:['Atendimento com IA','Triagem e contexto','Agendamento / reagendamento','Encaminhamento humano']},
  imobiliaria:{name:'Zion Qualificação Comercial',desc:'Qualificação de leads, organização de contexto, CRM e encaminhamento para o comercial.',base:[2200,3400],monthly:[497,797],features:['Qualificação de leads','CRM e histórico','Classificação de oportunidade','Visitas e encaminhamento']},
  reposicao:{name:'Zion Operação Inteligente',desc:'Automação operacional para estoque, reposição, regras de pedido e acompanhamento.',base:[2800,4500],monthly:[597,997],features:['Contagem orientada','Sugestão de pedido','Regras por produto','Histórico operacional']},
  personalizada:{name:'Zion Automação Sob Medida',desc:'Projeto desenhado a partir do processo real da empresa, com regras e integrações específicas.',base:[2500,4800],monthly:[497,1097],features:['Diagnóstico de processo','Fluxos personalizados','Regras de negócio','Integrações sob medida']}
};
const volumeFactors={small:1,medium:1.16,large:1.38};
const levelFactors={essential:.88,professional:1.08,advanced:1.42};
const levelLabels={essential:'Essencial',professional:'Profissional',advanced:'Avançado'};
const timelineMap={essential:'7–15 dias',professional:'10–20 dias',advanced:'15–30 dias'};
function brlRounded(v){const rounded=Math.ceil(v/100)*100;return rounded.toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0})}
function selectedValue(name){return document.querySelector(`input[name="${name}"]:checked`)?.value}
function selectedIntegrations(){return [...document.querySelectorAll('input[name="estimateIntegration"]:checked')].map(i=>i.value)}
function setEstimatorSolution(name,scroll=false){const input=document.querySelector(`input[name="estimateSolution"][value="${name}"]`);if(!input)return;input.checked=true;estimatorState.lastSolution=name;localStorage.setItem('zion_last_interest',name);updateEstimateProgress();if(scroll)document.querySelector('#investimento')?.scrollIntoView({behavior:'smooth',block:'start'})}
function updateEstimateProgress(){const complete=[selectedValue('estimateSolution'),selectedValue('estimateVolume'),selectedIntegrations().length,selectedValue('estimateLevel'),document.querySelector('#estimatePriority')?.value].filter(Boolean).length;const pct=Math.max(20,complete*20);const bar=document.querySelector('#estimateProgressBar');const txt=document.querySelector('#estimateProgressText');if(bar)bar.style.width=pct+'%';if(txt)txt.textContent=complete>=5?'Pronto para calcular':`Etapa ${Math.min(complete+1,5)} de 5`}
function projectEstimate(){
  const solution=selectedValue('estimateSolution')||'clinica',volume=selectedValue('estimateVolume')||'small',level=selectedValue('estimateLevel')||'professional',integrations=selectedIntegrations(),priority=document.querySelector('#estimatePriority')?.value||'tempo';
  const c=solutionCatalog[solution],vf=volumeFactors[volume],lf=levelFactors[level];const extra=Math.max(0,integrations.length-1);
  const lo=c.base[0]*vf*lf+extra*220,hi=c.base[1]*vf*lf+extra*420;
  const mlo=c.monthly[0]*(level==='essential'?.85:level==='advanced'?1.22:1)+(volume==='large'?120:volume==='medium'?50:0);
  const mhi=c.monthly[1]*(level==='essential'?.9:level==='advanced'?1.28:1)+(volume==='large'?220:volume==='medium'?90:0);
  const priorityLabel={tempo:'Reduzir tarefas repetitivas',vendas:'Responder mais rápido e perder menos oportunidades',controle:'Ter mais controle e histórico',escala:'Escalar a operação com eficiência'}[priority];
  const volumeLabel={small:'Até 500/mês',medium:'500–2.000/mês',large:'Mais de 2.000/mês'}[volume];
  const features=[...c.features,...integrations.filter(x=>!c.features.some(f=>f.toLowerCase().includes(x.toLowerCase()))).map(x=>'Integração: '+x)].slice(0,7);
  document.querySelector('#estimatePlaceholder').hidden=true;document.querySelector('#estimateContent').hidden=false;
  document.querySelector('#estimateComplexity').textContent=levelLabels[level];document.querySelector('#estimateProjectName').textContent=c.name;document.querySelector('#estimateProjectDescription').textContent=`Cenário ${levelLabels[level].toLowerCase()} • ${volumeLabel} • foco em ${priorityLabel.toLowerCase()}.`;
  document.querySelector('#estimateFeatures').innerHTML=features.map(x=>`<span>${x}</span>`).join('');document.querySelector('#estimateSetup').textContent=`${brlRounded(lo)} – ${brlRounded(hi)}`;document.querySelector('#estimateMonthly').textContent=`${brlRounded(mlo)} – ${brlRounded(mhi)}/mês`;document.querySelector('#estimateTimeline').textContent=timelineMap[level];document.querySelector('#estimateProfile').textContent=`Projeto ${levelLabels[level].toLowerCase()}`;
  const msg=[`Olá, Gabriel. Testei o site da Zion Automações e gostaria de uma proposta para este cenário:`,``,`Solução: ${c.name}`,`Volume: ${volumeLabel}`,`Personalização: ${levelLabels[level]}`,`Integrações: ${integrations.join(', ')||'A definir'}`,`Prioridade: ${priorityLabel}`,``,`Estimativa exibida no site:`,`Implantação: ${brlRounded(lo)} – ${brlRounded(hi)}`,`Operação/suporte: ${brlRounded(mlo)} – ${brlRounded(mhi)}/mês`,`Prazo: ${timelineMap[level]}`,``,`Quero entender como adaptar isso à minha empresa.`].join('\n');
  document.querySelector('#estimateWhatsapp').href='https://wa.me/5547988927391?text='+encodeURIComponent(msg);localStorage.setItem('zion_last_interest',solution);
  recordDemo('orcamento',`Estimativa • ${c.name} • ${brlRounded(lo)}–${brlRounded(hi)}`);toast('Projeto recomendado calculado');if(window.innerWidth<901)setTimeout(()=>document.querySelector('#estimateResult')?.scrollIntoView({behavior:'smooth',block:'center'}),120)
}
['estimateSolution','estimateVolume','estimateLevel','estimateIntegration'].forEach(name=>document.querySelectorAll(`input[name="${name}"]`).forEach(i=>i.addEventListener('change',updateEstimateProgress)));
document.querySelector('#estimatePriority')?.addEventListener('change',updateEstimateProgress);document.querySelector('#calculateProjectBtn')?.addEventListener('click',projectEstimate);document.querySelector('#recalculateProjectBtn')?.addEventListener('click',()=>{document.querySelector('#estimateContent').hidden=true;document.querySelector('#estimatePlaceholder').hidden=false;document.querySelector('#projectEstimator')?.scrollIntoView({behavior:'smooth',block:'start'})});
setEstimatorSolution(estimatorState.lastSolution);updateEstimateProgress();
document.querySelectorAll('.demo-tab').forEach(btn=>btn.addEventListener('click',()=>setEstimatorSolution(btn.dataset.demo)));
document.querySelectorAll('[data-jump]').forEach(el=>el.addEventListener('click',()=>setEstimatorSolution(el.dataset.jump)));
